project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Duh 165 Applied Statistics - Friday lecture"
  site-url: "https://njaalf.github.io/duh165/"

  sidebar:
      background: "#D9E3E4"
      logo: "images/icon.png"
      align: center
      style: "docked"
      search: false
      collapse-level: 1
      contents:
        - section: "Data and papers"
          contents: 
            - href: R/growth_reading.rds
              text: reading data
            - href: data/bigfive.csv
              text: bigfive normal
            - href: data/bigfive_nonnormal.csv
              text: bigfive non-normal
            - href: data/lundberg.pdf
              text: paper on causal estimands
            - href: data/improved.pdf
              text: paper on test statistics
format:
      html:
        theme:
          light: [cosmo, theme.scss]
          dark: [cosmo, theme-dark.scss]
        mainfont: "Atkinson Hyperlegible"
        code-copy: true
        code-overflow: wrap
        toc: false

editor: visual

